# Generated by Django 5.1.6 on 2025-05-25 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelViewSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('ast_query', models.JSONField()),
                ('response_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('channel_name', models.CharField(max_length=64)),
                ('has_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_view_subscriptions',
                'indexes': [models.Index(fields=['model_name', 'is_active'], name='model_view__model_n_35b336_idx'), models.Index(fields=['user', 'is_active'], name='model_view__user_id_0db430_idx'), models.Index(fields=['channel_name'], name='model_view__channel_2491a9_idx'), models.Index(fields=['last_checked'], name='model_view__last_ch_ec7822_idx')],
                'unique_together': {('user', 'channel_name')},
            },
        ),
    ]
