# Generated by Django 5.1.6 on 2025-05-25 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelViewSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('ast_query', models.JSONField()),
                ('response_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('channel_name', models.CharField(max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_view_subscriptions',
                'indexes': [models.Index(fields=['model_name'], name='model_view__model_n_16abfb_idx')],
                'unique_together': {('user', 'channel_name')},
            },
        ),
    ]
