# Generated by Django 5.1.6 on 2025-05-31 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statezero', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelViewSubscription',
        ),
    ]
