# Generated by Django 5.1.6 on 2025-11-11 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statezero', '0002_delete_modelviewsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ast', models.JSONField(help_text='The AST that generates this query')),
                ('last_result', models.JSONField(blank=True, help_text='Last cached result', null=True)),
                ('anonymous_users_allowed', models.BooleanField(default=False, help_text='Whether anonymous users can subscribe to this query')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, help_text='Last time an update was pushed to subscribers', null=True)),
                ('users', models.ManyToManyField(blank=True, help_text='Authenticated users subscribed to this query', related_name='query_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'statezero_query_subscription',
                'indexes': [models.Index(fields=['hashed_cache_key'], name='statezero_q_hashed__c635b1_idx'), models.Index(fields=['-updated_at'], name='statezero_q_updated_1fc026_idx')],
            },
        ),
    ]
