# Generated by Django 5.1.6 on 2025-11-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statezero', '0003_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='querysubscription',
            name='statezero_q_updated_1fc026_idx',
        ),
        migrations.RemoveField(
            model_name='querysubscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='querysubscription',
            name='last_pushed_at',
        ),
        migrations.RemoveField(
            model_name='querysubscription',
            name='updated_at',
        ),
    ]
