# Generated by Django 5.1.6 on 2025-11-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statezero', '0004_remove_querysubscription_statezero_q_updated_1fc026_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysubscription',
            name='model_name',
            field=models.CharField(db_index=True, default='unknown', max_length=255),
        ),
    ]
