# Generated by Django 5.1.6 on 2025-11-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statezero', '0005_querysubscription_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysubscription',
            name='namespace',
            field=models.JSONField(default=dict, help_text='Namespace filters for determining when to re-execute this query'),
        ),
    ]
