# Generated by Django 5.1.6 on 2025-11-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statezero', '0006_querysubscription_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysubscription',
            name='query_type',
            field=models.CharField(choices=[('read', 'Read (Queryset)'), ('aggregate', 'Aggregate (Metric)')], db_index=True, default='read', help_text="Type of query: 'read' for querysets, 'aggregate' for metrics", max_length=20),
        ),
    ]
