# Generated by Django 5.1.6 on 2025-11-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statezero', '0007_querysubscription_query_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysubscription',
            name='pk_index',
            field=models.JSONField(default=dict, help_text='Optimized index of PKs by model for fast lookups'),
        ),
    ]
