# Generated by Django 5.1.6 on 2025-11-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statezero', '0008_querysubscription_pk_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysubscription',
            name='needs_rerun',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this subscription needs to be re-executed due to data changes'),
        ),
    ]
