# Generated by Django 5.1 on 2025-02-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dummymodel",
            name="value",
            field=models.IntegerField(default=0),
        ),
    ]
