# Generated by Django 5.1.6 on 2025-03-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_custompkmodel_custom_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepmodellevel1',
            name='comprehensive_models',
            field=models.ManyToManyField(blank=True, related_name='deep_models', to='django_app.comprehensivemodel'),
        ),
    ]
