# Generated by Django 5.1.6 on 2025-11-06 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_filetest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_stay_arrival', models.IntegerField(blank=True, null=True)),
                ('min_stay_through', models.IntegerField(blank=True, null=True)),
                ('max_stay', models.IntegerField(blank=True, null=True)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('stop_sell', models.BooleanField(default=False)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to='django_app.rateplan')),
            ],
            options={
                'indexes': [models.Index(fields=['rate_plan', 'date'], name='django_app__rate_pl_292148_idx'), models.Index(fields=['date'], name='django_app__date_cc99cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('rate_plan', 'date'), name='unique_rate_plan_date')],
            },
        ),
    ]
