# Generated by Django 5.1 on 2025-02-26 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_app",
            "0004_alter_comprehensivemodel_id_alter_deepmodellevel1_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPKModel",
            fields=[
                ("custom_pk", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ModelWithCustomPKRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "custom_pk_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_models",
                        to="django_app.custompkmodel",
                    ),
                ),
            ],
        ),
    ]
