# Generated by Django 5.1 on 2025-02-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0005_custompkmodel_modelwithcustompkrelation"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameFilterCustomPKModel",
            fields=[
                ("custom_pk", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
