# Generated by Django 5.1.15 on 2026-01-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_comprehensivemodel_nullable_money_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedFieldRelatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_code', models.CharField(max_length=100)),
                ('admin_only_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelWithRestrictedFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_code', models.CharField(max_length=100)),
                ('admin_only_field', models.CharField(max_length=100)),
                ('restricted_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricted_models', to='django_app.restrictedfieldrelatedmodel')),
            ],
        ),
    ]
