# Generated by Django 5.1.15 on 2026-01-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_restrictedfieldrelatedmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithrestrictedfields',
            name='admin_only_field',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelwithrestrictedfields',
            name='internal_code',
            field=models.CharField(default='internal', max_length=100),
        ),
        migrations.AlterField(
            model_name='restrictedfieldrelatedmodel',
            name='admin_only_field',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restrictedfieldrelatedmodel',
            name='internal_code',
            field=models.CharField(default='internal', max_length=100),
        ),
    ]
