# Generated by Django 5.1.15 on 2026-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_historytestmodel_historicalhistorytestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummymodel',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
