# Generated by Django 5.1.15 on 2026-01-18 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_alter_modelwithrestrictedfields_admin_only_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2MDepthTestLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='M2MDepthTestLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level2s', models.ManyToManyField(blank=True, related_name='level1s', to='django_app.m2mdepthtestlevel2')),
            ],
        ),
        migrations.CreateModel(
            name='M2MDepthTestLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m2m_depth_level3s', to='django_app.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='m2mdepthtestlevel2',
            name='level3s',
            field=models.ManyToManyField(blank=True, related_name='level2s', to='django_app.m2mdepthtestlevel3'),
        ),
    ]
