# Generated by Django 5.1.15 on 2026-02-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_alter_dummymodel_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecretParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('secret', models.CharField(default='classified', max_length=100)),
                ('public_info', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecretGrandchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandchildren', to='django_app.secretchild')),
            ],
        ),
        migrations.AddField(
            model_name='secretchild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_app.secretparent'),
        ),
    ]
