# Generated by Django 5.1.6 on 2025-03-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_childtestmodel_parenttestmodel_grandchildtestmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childtestmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_app.parenttestmodel'),
        ),
        migrations.AlterField(
            model_name='grandchildtestmodel',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grandchildren', to='django_app.childtestmodel'),
        ),
    ]
