# Generated by Django 5.1.15 on 2026-02-22 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_tag_cost_tag_cost_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorTestParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorTestUniqueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorTestCompoundUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'rank'), name='unique_group_rank')],
            },
        ),
        migrations.CreateModel(
            name='ErrorTestOneToOneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one_child', to='django_app.errortestparent')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorTestProtectedChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protected_children', to='django_app.errortestparent')),
            ],
        ),
    ]
