# Generated by Django 5.1.15 on 2026-02-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_errortestparent_errortestuniquemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateOnlyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
